### ISSUE TITLE
Cannot compile - setScore64 error

### ISSUE THREAD

**Issue by okaybmd** [SempaiGames/openfl-gpg#13]
In GooglePlayGames.hx, there is this function:

```haxe
public static function setScore64(id:String, score:Int64):Bool {
	return javaSetScore(id, score.high, score.low);
}
```
I get these errors:

> Cannot access private field high    Path: c:\HaxeToolkit\haxe\lib\openfl-gpg\1,3,0\extension\gpg
> Cannot access private field low    Path: c:\HaxeToolkit\haxe\lib\openfl-gpg\1,3,0\extension\gpg

**Comment by fbricker** [comment]
Hi, if you see this error, I assume you are an old version of haxe (like haxe 3.1.X or lower...)
Since haxe 3.2, Int64 API has changed, and unfortunately, there's no implementation that will compile with both (haxe 3.2 and 3.1 or lower in regards to libraries using Int64 type).

You should either update to haxe 3.2+ or modify your local copy of the library.

If you decide to modify your local copy, you shoud replace:
```haxe
score.high  =>  Int64.getHigh(score)
and
score.low  =>  Int64.getLow(score)
```

Please try this and let me know if this solves your issue.
